steps:
  - name: "Python black"
    command: "black . --check"
    plugins:
      - docker-compose#v5.2.0:
          run: backend
  - name: "Python isort"
    command: "isort . --check"
    plugins:
      - docker-compose#v5.2.0:
          run: backend
  - name: "Python pytest"
    command: "pytest ."
    plugins:
      - docker-compose#v5.2.0:
          run: backend