steps:
  - group: ":python: backend"
    key: backend
    steps:
      - name: ":mypy: mypy"
        command: mypy app
        plugins:
          - docker-compose#v5.2.0:
              run: bk
      - name: ":python-black: black"
        command: black app --check
        plugins:
          - docker-compose#v5.2.0:
              run: bk
      - name: ":isort: isort"
        command: isort --check-only app
        plugins:
          - docker-compose#v5.2.0:
              run: bk
      - name: ":python: flake8"
        command: flake8 app
        plugins:
          - docker-compose#v5.2.0:
              run: bk
      - name: ":pytest: pytest"
        command: pytest .
        plugins:
          - docker-compose#v5.2.0:
              run: bk
              environment:
                - BUILDKITE_BUILD_ID
                - BUILDKITE_BUILD_NUMBER
                - BUILDKITE_JOB_ID
                - BUILDKITE_BRANCH
                - BUILDKITE_COMMIT
                - BUILDKITE_MESSAGE
                - BUILDKITE_BUILD_URL
                - BUILDKITE_ANALYTICS_TOKEN
  - group: ":node: frontend"
    key: frontend
    steps:
      - name: ":playwright: playwright run tests"
        commands:
          - pnpm install
          - pnpm run start & npx playwright test
        plugins:
          - docker-compose#v5.2.0:
              run: fe
              environment:
                - BUILDKITE_BUILD_ID
                - BUILDKITE_BUILD_NUMBER
                - BUILDKITE_JOB_ID
                - BUILDKITE_BRANCH
                - BUILDKITE_COMMIT
                - BUILDKITE_MESSAGE
                - BUILDKITE_BUILD_URL
                - BUILDKITE_ANALYTICS_TOKEN_FE
          - artifacts:
              "frontend/playwright-report/*": playwright-report
