steps:
  - name: ":mypy:"
    command: mypy app
    plugins:
      - docker-compose#v5.2.0:
          run: bk
  - name: ":python-black:"
    command: black app --check
    plugins:
      - docker-compose#v5.2.0:
          run: bk
  - name: :"isort:"
    command: isort --check-only app
    plugins:
      - docker-compose#v5.2.0:
          run: bk
  - name: ":python: flake8"
    command: flake8 app
    plugins:
      - docker-compose#v5.2.0:
          run: bk
  - name: ":pytest:"
    command: pytest .
    plugins:
      - docker-compose#v5.2.0:
          run: bk
