steps:
  - name: "Prepare envs"
    command: ./prepare_ci.sh
    artifact_paths: "backend/.env"

  - wait: ~
    continue_on_failure: true
  - name: "Python black"
    command: "black . --check"
    plugins:
      - docker-compose#v3.7.0:
          run: web
  - name: "Python isort"
    command: "isort . --check"
    plugins:
      - docker-compose#v3.7.0:
          run: web
  - name: "Python pytest"
    command: "pytest ."
    plugins:
      - docker-compose#v3.7.0:
          run: web