steps:
  - name: Python black
    command: black . --check
    plugins:
      - docker-compose#v5.2.0:
          run: bk
  - name: Python isort
    command: isort . --check
    plugins:
      - docker-compose#v5.2.0:
          run: bk
  - name: Python pytest
    command: pytest .
    plugins:
      - docker-compose#v5.2.0:
          run: bk